sudo: required
dist: trusty
addons:
  hosts:
    - rstats.local
    - memcached.local
virtualenv:
  system_site_packages: true
language: python
python:
  - "2.7"
before_install:
  # Stop supplied 9.1 postgresql as postgis 
  - sudo /etc/init.d/postgresql stop
  - sudo ln -s `pwd` /opt/rtstats
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-matplotlib python-psycopg2 python-numpy python-memcache 
  - sudo apt-get install apache2 libapache2-mod-wsgi memcached postgis
  - sudo service postgresql start 9.6
  - sudo service memcached start
  - sudo a2enmod headers rewrite proxy cgi
  - echo '<VirtualHost *:80>' | sudo tee /etc/apache2/sites-enabled/rtstats.conf > /dev/null
  - cat config/rtstats-vhost.inc | sudo tee -a /etc/apache2/sites-enabled/rtstats.conf > /dev/null
  - echo '</VirtualHost>' | sudo tee -a /etc/apache2/sites-enabled/rtstats.conf > /dev/null
  - sudo service apache2 restart || sudo cat /var/log/apache2/error.log
  # apt provided requests, pandas is too old
  - "sudo pip install requests"
  - "sudo pip install pandas"
  - curl http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz | sudo gunzip - > /tmp/GeoLiteCity.dat
install:
  - "pip install --upgrade pip"
before_script:
  - cd config; cp settings.json-in settings.json; cd ..
  - cd database; sh bootstrap.sh
  - python schema_manager.py
  - cd ..
script:
  - cat test/rtstats_example.txt | python app/run.py
  - python scripts/assign_hostname_geom.py
  - sudo cat /var/log/apache2/error.log
